# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  # Define your application as a service called "server"
  server:
    build:
      context: .
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
    depends_on:
      mysql:
        condition: service_healthy

  # Example of how to define a MySQL database that your application can use
  mysql:
    image: mysql:8.0
    container_name: backend-shopper
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: rooy
      MYSQL_DATABASE: db
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - 3307
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

# Volume to persist the MySQL database data between container restarts
volumes:
  mysql_data:


